# Generated by Django 6.0.4 on 2026-04-29 06:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория оборудования',
                'verbose_name_plural': 'Категории оборудования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('inventory_number', models.CharField(max_length=100, unique=True, verbose_name='Инвентарный номер')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.FileField(blank=True, upload_to='equipment/', verbose_name='Фото')),
                ('status', models.CharField(choices=[('available', 'Доступно'), ('maintenance', 'На обслуживании'), ('out_of_order', 'Неисправно'), ('inactive', 'Неактивно')], default='available', max_length=20, verbose_name='Статус')),
                ('slot_duration_minutes', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(1440)], verbose_name='Длительность слота, мин')),
                ('requires_training', models.BooleanField(default=True, verbose_name='Требуется инструктаж')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_items', to='equipment.equipmentcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentDowntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Начало недоступности')),
                ('end_at', models.DateTimeField(verbose_name='Окончание недоступности')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_downtimes', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtimes', to='equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Период недоступности оборудования',
                'verbose_name_plural': 'Периоды недоступности оборудования',
                'ordering': ['-start_at'],
            },
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status'], name='equipment_e_status_fb8540_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['category', 'status'], name='equipment_e_categor_149399_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['name'], name='equipment_e_name_8baf3a_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentdowntime',
            index=models.Index(fields=['equipment', 'start_at', 'end_at'], name='equipment_e_equipme_2f97fa_idx'),
        ),
    ]
