# Generated by Django 6.0.4 on 2026-04-29 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Начало брони')),
                ('end_at', models.DateTimeField(verbose_name='Окончание брони')),
                ('status', models.CharField(choices=[('pending', 'На подтверждении'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена пользователем'), ('completed', 'Завершена'), ('expired', 'Истекла')], default='pending', max_length=20, verbose_name='Статус')),
                ('request_comment', models.TextField(blank=True, verbose_name='Комментарий к заявке')),
                ('staff_comment', models.TextField(blank=True, verbose_name='Комментарий персонала')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отказа')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Причина отмены')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверено')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Архивировано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='equipment.equipment', verbose_name='Оборудование')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['start_at', 'equipment__name'],
                'indexes': [models.Index(fields=['equipment', 'start_at', 'end_at'], name='reservation_equipme_8110b6_idx'), models.Index(fields=['status', 'start_at'], name='reservation_status_e8c444_idx'), models.Index(fields=['user', 'status'], name='reservation_user_id_b23f11_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='reservation_end_after_start')],
            },
        ),
    ]
