# Generated by Django 6.0.4 on 2026-04-29 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_created', 'Пользователь создан'), ('user_role_changed', 'Роль пользователя изменена'), ('training_status_changed', 'Статус инструктажа изменен'), ('equipment_created', 'Оборудование создано'), ('equipment_status_changed', 'Статус оборудования изменен'), ('reservation_created', 'Бронирование создано'), ('reservation_approved', 'Бронирование подтверждено'), ('reservation_rejected', 'Бронирование отклонено'), ('reservation_cancelled', 'Бронирование отменено'), ('notification_created', 'Уведомление создано')], max_length=50, verbose_name='Действие')),
                ('entity_type', models.CharField(max_length=50, verbose_name='Тип сущности')),
                ('entity_id', models.PositiveBigIntegerField(verbose_name='ID сущности')),
                ('entity_label', models.CharField(blank=True, max_length=255, verbose_name='Название сущности')),
                ('description', models.TextField(verbose_name='Описание')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx')],
            },
        ),
    ]
